### ISSUE TITLE
LG G2 4.4.2 very slow screen update

### ISSUE THREAD

**Issue by godlatro** [yangh/sevensquare#18]
LG G2 4.4.2 
Kernel 3.4.0
It work!
I see my screen, i can click on it, camera work too
But when I open something, screen update can wait for 3-10 seconds, and then update
BUT when I click - my phone get clicks immediately

**Comment by elsandosgrande** [comment]
Well, the lag goes both ways for me. Oh, and switching from AON to AOU (ADB over Network/USB respectively) doesn't help, since my cable is loose (that, or the port on my phone is worn down, same result either way), so it keeps disconnecting and reconnecting. There should be an option to use Miracast like on Windows 10 in its Connect app. 
_Wonders if it's important to mention that his phone is a Galaxy S4 running an Oreo 8.1.0 ROM, Resurrection Remix OS_

**Comment by gabretana** [comment]
I think this depends of screen resolution and phone specs, the convertion to png format is very slow.
For example my old phone with a screen resolution of 480x800 the lag is about 2-3 seconds but with a "new" phone with 1280x720 the lag is 3-4 seconds and it's even more displaying an image with many colors but with a black screen is super quickly

**Comment by yangh** [comment]
Fixed reconnect issue in latest commit 1333e50, let's keep only one lag issue open.
